const fs = require('fs');
const path = require('path');
const pngPath = path.join(__dirname, 'images', 'logo', 'logo.png');
const icoPath = path.join(__dirname, 'favicon.ico');
const pngData = fs.readFileSync(pngPath);
const imageOffset = 6 + 16;
const ico = Buffer.alloc(imageOffset + pngData.length);
ico.writeUInt16LE(0, 0);
ico.writeUInt16LE(1, 2);
ico.writeUInt16LE(1, 4);
ico.writeUInt8(200, 6);
ico.writeUInt8(200, 7);
ico.writeUInt8(0, 8);
ico.writeUInt8(0, 9);
ico.writeUInt16LE(1, 10);
ico.writeUInt16LE(32, 12);
ico.writeUInt32LE(pngData.length, 14);
ico.writeUInt32LE(imageOffset, 18);
pngData.copy(ico, imageOffset);
fs.writeFileSync(icoPath, ico);
console.log('favicon.ico generated at', icoPath);
